name: svart
version: 0.1.0
description: Svart is an embedded (in Dart) domain-specific language for
  describing binary circuits, generating a strict subset of SystemVerilog and
  easily interacting with external tools.
repository: https://github.com/chykon/svart
issue_tracker: https://github.com/chykon/svart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.4
  very_good_analysis: ^5.0.0+1
