name: Basic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  basic-checks:
    name: Basic Checks
    timeout-minutes: 30
    runs-on: ubuntu-22.04
